-- إضافة بيانات تجريبية للوسطاء
INSERT INTO land_brokers (id, name, short_name, phone, email, whatsapp_number, areas_specialization, office_name, office_location, activity_status, deals_count, total_sales_amount, notes, language, created_at) VALUES
(
  gen_random_uuid(),
  'علي نصر',
  'علي',
  '+971586514063',
  'ali.nasr@example.com',
  '+971586514063',
  ARRAY['المناطق السكنية', 'المناطق التجارية'],
  'مكتب علي نصر للعقارات',
  'دبي - شارع الشيخ زايد',
  'active',
  15,
  2500000,
  'وسيط نشط ومحترف',
  'arabic',
  NOW()
),
(
  gen_random_uuid(),
  'عبد المالك خالد',
  'عبد المالك',
  '+971586514064',
  'abdul.malik@example.com',
  '+971586514064',
  ARRAY['المناطق السكنية', 'المناطق الصناعية'],
  'مكتب عبد المالك للعقارات',
  'أبو ظبي - شارع الكورنيش',
  'active',
  12,
  1800000,
  'وسيط محترف في أبو ظبي',
  'arabic',
  NOW()
),
(
  gen_random_uuid(),
  'محمد كامل',
  'محمد',
  '+971522001189',
  'mohammed.kamel@example.com',
  '+971522001189',
  ARRAY['المناطق السكنية', 'المناطق السياحية'],
  'مكتب محمد كامل للعقارات',
  'الشارقة - شارع الملك فيصل',
  'active',
  8,
  1200000,
  'وسيط متخصص في الشارقة',
  'arabic',
  NOW()
),
(
  gen_random_uuid(),
  'أحمد حسن',
  'أحمد',
  '+971501234567',
  'ahmed.hassan@example.com',
  '+971501234567',
  ARRAY['المناطق التجارية', 'المناطق الصناعية'],
  'مكتب أحمد حسن للعقارات',
  'عجمان - شارع الشيخ راشد',
  'medium',
  6,
  800000,
  'وسيط متوسط النشاط',
  'arabic',
  NOW()
),
(
  gen_random_uuid(),
  'فاطمة علي',
  'فاطمة',
  '+971502345678',
  'fatima.ali@example.com',
  '+971502345678',
  ARRAY['المناطق السكنية'],
  'مكتب فاطمة علي للعقارات',
  'رأس الخيمة - شارع الشيخ محمد',
  'low',
  3,
  400000,
  'وسيطة جديدة في السوق',
  'arabic',
  NOW()
);
